### ISSUE TITLE
daemon crash with "concurrent map write" in collapseFunction

### ISSUE THREAD

**Issue by Charles546** [honeydipper/honeydipper#354]
Daemon crashes in `collapseFunction` call in `operator` service with `concurrent map write` error message.

```
 Error
2020-12-09 11:37:42.509 PST
fatal error: concurrent map writes
Info
2020-12-09 11:37:42.509 PST
19:37:42.509 daemon.operatorRoute ▶ INFO 8362 [operator] routing message rpc.return
Error
2020-12-09 11:37:42.509 PST
fatal error: concurrent map writes
Info
2020-12-09 11:37:42.509 PST
19:37:42.509 daemon.operatorRoute ▶ INFO 8361 [operator] routing message rpc.return
Error
2020-12-09 11:37:42.517 PST
Error
2020-12-09 11:37:42.517 PST
goroutine 191346 [running]:
Error
2020-12-09 11:37:42.517 PST
runtime.throw(0xd8ccc6, 0x15)
Error
2020-12-09 11:37:42.517 PST
/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00086cfd0 sp=0xc00086cfa0 pc=0x437cf2
Error
2020-12-09 11:37:42.517 PST
runtime.mapassign(0xc90260, 0xc001084210, 0xc0008c2670, 0xc0004dc780)
Error
2020-12-09 11:37:42.517 PST
/usr/local/go/src/runtime/map.go:676 +0x5a7 fp=0xc00086d050 sp=0xc00086cfd0 pc=0x411cc7
Error
2020-12-09 11:37:42.517 PST
reflect.mapassign(0xc90260, 0xc001084210, 0xc0008c2670, 0xc001177580)
Error
2020-12-09 11:37:42.517 PST
/usr/local/go/src/runtime/map.go:1319 +0x3f fp=0xc00086d080 sp=0xc00086d050 pc=0x4666bf
Error
2020-12-09 11:37:42.517 PST
reflect.Value.SetMapIndex(0xc90260, 0xc001084210, 0x15, 0xc557e0, 0xc0008c2670, 0x98, 0xc7b660, 0xc001177580, 0x94)
Error
2020-12-09 11:37:42.517 PST
/usr/local/go/src/reflect/value.go:1696 +0x27c fp=0xc00086d100 sp=0xc00086d080 pc=0x4a069c
Error
2020-12-09 11:37:42.517 PST
github.com/honeydipper/honeydipper/pkg/dipper.RecursiveWithPrefix(0xc90260, 0xc001084210, 0x0, 0x0, 0xc557e0, 0xc0008c2670, 0xc557e0, 0xc000a7d080, 0xc00086d518)
Error
2020-12-09 11:37:42.517 PST
/build/pkg/dipper/mapUtils.go:186 +0x738 fp=0xc00086d288 sp=0xc00086d100 pc=0x840d38
Error
2020-12-09 11:37:42.517 PST
github.com/honeydipper/honeydipper/pkg/dipper.RecursiveWithPrefix(0x0, 0x0, 0x0, 0x0, 0xc557e0, 0xe6eef0, 0xc90260, 0xc001084210, 0xc00086d518)
Error
2020-12-09 11:37:42.517 PST
/build/pkg/dipper/mapUtils.go:157 +0x472 fp=0xc00086d410 sp=0xc00086d288 pc=0x840a72
Error
2020-12-09 11:37:42.517 PST
github.com/honeydipper/honeydipper/pkg/dipper.Recursive(...)
Error
2020-12-09 11:37:42.517 PST
/build/pkg/dipper/mapUtils.go:137
Error
2020-12-09 11:37:42.517 PST
github.com/honeydipper/honeydipper/internal/service.collapseFunction(0xc00086d810, 0xc00086d8b0, 0xc0012888a0, 0xc, 0xc0001cba88, 0x1, 0x0, 0xea5b40)
Error
2020-12-09 11:37:42.517 PST
/build/internal/service/operator.go:200 +0x6a5 fp=0xc00086d6e8 sp=0xc00086d410 pc=0xbc9985 
```

**Comment by Charles546** [comment]
https://github.com/honeydipper/honeydipper/blob/5918d0f56cdca8058ae5689ad4d91f206f3ad898/internal/service/operator.go#L201

This is the line we need to think about how to fix.

**Comment by Charles546** [comment]
Seems having similar issue with `workflow.mergeContext`

```
 Error
2020-12-07 16:03:41.456 PST
github.com/honeydipper/honeydipper/pkg/dipper.MergeMap(0xc00194bd40, 0xc90260, 0xc0014cf1d0, 0x94)
Error
2020-12-07 16:03:41.456 PST
/build/pkg/dipper/mapUtils.go:385 +0x3f fp=0xc000c26e28 sp=0xc000c26df8 pc=0x8430ff
Error
2020-12-07 16:03:41.456 PST
github.com/honeydipper/honeydipper/internal/workflow.(*Session).mergeContext(0xc0016ba690, 0xc0000feca0, 0x3, 0x4)
Error
2020-12-07 16:03:41.456 PST
/build/internal/workflow/continue.go:91 +0x72 fp=0xc000c26e88 sp=0xc000c26e28 pc=0xbb66d2
Error
2020-12-07 16:03:41.456 PST
github.com/honeydipper/honeydipper/internal/workflow.(*Session).continueExec(0xc0016ba690, 0xc000bfd560, 0xc0000feca0, 0x3, 0x4)
Error
2020-12-07 16:03:41.456 PST
/build/internal/workflow/continue.go:303 +0x53 fp=0xc000c26ef0 sp=0xc000c26e88 pc=0xbb8bb3
```
